name: PR Validation

on:
  pull_request:
    branches: [main]
    paths: ['packer/**', 'examples/**']
  workflow_dispatch:

permissions:
  contents: read

jobs:
  packer_checks:
    name: Packer Checks
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 1
          persist-credentials: false

      - name: Perform Secrets Scan
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          GITLEAKS_CONFIG: "${{ github.workspace }}/.github/config/gitleaks.toml"
          GITLEAKS_ENABLE_SUMMARY: true
          GITLEAKS_VERSION: 'latest'

      - name: Get Packer version
        working-directory: "${{ github.workspace }}/packer/"
        shell: bash
        run: "bash ${{ github.workspace }}/.github/scripts/get_packer_version.sh"

      - name: Setup Packer
        uses: hashicorp/setup-packer@v3.1.0
        with:
          version: "${{ env.PACKER_VERSION }}"

      - name: Packer init
        working-directory: "${{ github.workspace }}/packer/"
        run: packer init .

      - name: Run packer fmt (check)
        working-directory: "${{ github.workspace }}/packer/"
        run: |
          packer fmt -check -recursive .
          if [ $? -ne 0 ]; then
            echo "::error::Packer files need formatting. Run: packer fmt -recursive ./packer"
            exit 1
          fi

      - name: Run packer validate
        working-directory: "${{ github.workspace }}/packer/"
        run: |
          if ! packer validate                                                     \
            -var-file="${{ github.workspace }}/examples/rocky-linux-9.pkrvars.hcl" \
            -var-file="${{ github.workspace }}/examples/secrets.pkrvars.hcl"       \
            "${{ github.workspace }}/packer/"; then
            echo "::error::Packer files are invalid"
            exit 1
          fi
